### ISSUE TITLE
Inconsistency of url prefixing slash when using different search methods

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-lib#110]
The content url returned by different search method is not the same, even if the same article is fetched. For example:

- if using `Searcher`, the value returned by `Result::get_url` is `A/article.html`
- if using `getNextSuggestion`, the url is `/A/article.html`

It would be a good idea to have both search methods return the same path for better consistency.

Test zim: wikivoyage_en_all_2017-10.zim
Search text: th

**Comment by kelson42** [comment]
I think with the URL should all start with "/". If a patch is relative, so without "/", then it is context dependant. This has no sense at the kiwix-lib level.
