### ISSUE TITLE
EXC_BAD_ACCESS when searching in certain zim files

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-lib#115]
libkiwix crashed when `Search::getNextResult()` is executed when using an external idx.
File in question: [kiwix-0.9+wikipedia_eo_all_nopic_2018-01.zip](https://download.kiwix.org/portable/wikipedia/kiwix-0.9+wikipedia_eo_all_nopic_2018-01.zip)

See backtrace below:
```
* thread #6, queue = 'run.kit.procedure.ProcedureKit.Procedure.EventQueue', stop reason = EXC_BAD_ACCESS (code=1, address=0x7f)
    frame #0: 0x000000010436ab48 Kiwix`zim::Search::end(this=0x0000000000000000) const at search.cpp:334
    frame #1: 0x00000001043a775c Kiwix`kiwix::Searcher::getNextResult(this=0x00000001c8150490) at searcher.cpp:253
  * frame #2: 0x00000001042351d4 Kiwix`::-[ZimMultiReader getNextIndexSearchResult](self=0x00000001c000d750, _cmd="getNextIndexSearchResult") at ZimMultiReader.mm:215
    frame #3: 0x000000010426e440 Kiwix`ZimMultiReader.getNextIndexSearchResult(self=0x00000001c000d750) at ZimMultiReader.swift:45
    frame #4: 0x0000000104307f5c Kiwix`SearchProcedure.addIndexedSearchResults(self=0x00000001c41bdc00) at SearchProcedure.swift:36
    frame #5: 0x0000000104307d3c Kiwix`SearchProcedure.execute(self=0x00000001c41bdc00) at SearchProcedure.swift:27
```

Also note that the console prints `No steemming for language 'eo'` during the search process, but I am not sure during which function call. 

EXC_BAD_ACCESS means we are trying to access a object that has already been dealloced. See [What Is EXC_BAD_ACCESS and How to Debug It](https://code.tutsplus.com/tutorials/what-is-exc_bad_access-and-how-to-debug-it--cms-24544)

**Comment by mgautierfr** [comment]
Fixed by #121.
