### ISSUE TITLE
Error in meson installation by following README

### ISSUE THREAD

**Issue by RohanBh** [kiwix/kiwix-lib#118]
### Error
```bash
$ sudo pip install meson
The directory '/home/rohan/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/rohan/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting meson
  Downloading meson-0.45.0.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 90kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-TSz2eD/meson/setup.py", line 20, in <module>
        from mesonbuild.coredata import version
      File "mesonbuild/coredata.py", line 15, in <module>
        from . import mlog
      File "mesonbuild/mlog.py", line 82
        print(*args, **kwargs)
              ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-TSz2eD/meson/
```
### Fix
The [Official Installation guide](http://mesonbuild.com/Getting-meson.html) of meson uses `pip3` for installation.
`pip3 install meson`

**Comment by mgautierfr** [comment]
Thanks for reporting.

Do you think you can do a PR ?

**Comment by RohanBh** [comment]
Yes. I was going to do that after I successfully compile kiwixlib.

**Comment by utlww** [comment]
Hi, it seems I still got same error with pip3. I'm using conda and have a python3 env (so pip is actually pip3). Below are the error msg and related info. Any help is appreciated! 

(py3) [ec2-user@ip-172-31-42-162 ~]$ which python
alias python='python3'
        ~/miniconda3/bin/python3
(py3) [ec2-user@ip-172-31-42-162 ~]$ pip show pip
Name: pip
Version: 10.0.1
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: python-virtualenv@groups.google.com
License: MIT
Location: /home/ec2-user/miniconda3/lib/python3.6/site-packages
Requires:
Required-by:
(py3) [ec2-user@ip-172-31-42-162 ~]$ sudo pip install meson
Collecting meson
  Using cached https://files.pythonhosted.org/packages/30/26/036340ecd1061d5c31f0eba4573b2ce63a28cd406c589d575322cb3279f5/meson-0.46.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3udygv/meson/setup.py", line 20, in <module>
        from mesonbuild.coredata import version
      File "mesonbuild/coredata.py", line 15, in <module>
        from . import mlog
      File "mesonbuild/mlog.py", line 84
        print(*args, **kwargs)
              ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-3udygv/meson/

**Comment by mgautierfr** [comment]
You are probably running pip2 not pip3.
This is probably because of the `sudo`. (If you are in a virtual env, you probably not need root right to install in it)

If I'm right, `sudo pip show pip` should show that you are using your python2 installation.

**Comment by bejota** [comment]
Got the same error as [RohanBh](https://github.com/kiwix/kiwix-lib/issues/118#issue-303602334), then pip3 installed Ninja. Now I get another error:

Verify python3:
```
user@server: /usr/local/bin/pip3 -V
pip 19.2.1 from /usr/local/lib/python3.5/site-packages/pip (python 3.5)
```

Attempt install:
```
user@server: sudo /usr/local/bin/pip3 install meson
Collecting meson
  Using cached https://files.pythonhosted.org/packages/18/ba/0f3d6aef4ba484f59e4d3a00678c4322295976ec1db35c5929a8c1901099/meson-0.51.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.5 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fjx_feqh/meson/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fjx_feqh/meson/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-fjx_feqh/meson/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fjx_feqh/meson/setup.py", line 24, in <module>
        from mesonbuild.coredata import version
      File "/tmp/pip-install-fjx_feqh/meson/mesonbuild/coredata.py", line 21, in <module>
        from .mesonlib import (
      File "/tmp/pip-install-fjx_feqh/meson/mesonbuild/mesonlib.py", line 393, in <module>
        class PerMachineDefaultable(PerMachine[typing.Optional[_T]]):
      File "/usr/local/lib/python3.5/typing.py", line 913, in __new__
        "non-type-variable %s" % bp)
    TypeError: Cannot inherit from a generic class parameterized with non-type-variable typing.Union[~_T, NoneType]
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
