### ISSUE TITLE
Replace aria2c binary RPC calls by libaria2

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#13]
Would be a lot nicer and efficient

**Comment by mgautierfr** [comment]
You're right but it seems that aria is used only by components of kiwix and never by kiwix-lib or kiwix-tools.

We should simply remove aria2c from the dependencies of kiwix-lib and keep it on kiwix(desktop) side.

**Comment by kelson42** [comment]
@mgautierfr that would definitly be a good step in the right direction.
