### ISSUE TITLE
provide a way to get category

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-lib#130]
In kiwix for iOS app, to improve usability, I try to group zim files by category, e.g., wikipedia, Wikivoyage, stack exchange, etc. 

I currently rely on name property and file name to figure out the category. But they are not reliable since name property does not have a predefined format and file name could be changed.

It would be great to have an API in libkiwix to get the category of zim files.

**Comment by kelson42** [comment]
We won't create a concept of category because we do not really need it IMO and more agnostic/standard way of accessing content through the library should be enough. On the top of this I do not want us to maintain a hierarchy of content like any public library does. Everything should run based on the tags.

**Comment by automactic** [comment]
From the feedback I gathered from users who have tried kiwix iOS app 1.9, they like the grouped by category version of the library much better. 

Let's take English language zim files for example, as of Apr 13, 2018. There is got to be close to 100 of these files. It would be a very poor user experience to just list all 100 of them one after another on screen. The same problem exists with the [online wiki](http://wiki.kiwix.org/wiki/Content)

On the other hand, if we can categorize them, we can show 

A good UX, I think, is not to provide user with too many choices at a time.

**Comment by automactic** [comment]
I also would **not** suggest to just jam every new attribute in tags. Refer to #131 for more detail.

**Comment by kelson42** [comment]
It is for sure a good idea to provide "categories" like you have done in 1.9 for iOS. Even if this is not really a category system, it is just a way to pre-filter content.

The Kiwix lib is not really the place to discuss how to present content but if you have an idea of presentation on iOS that you can not do using the current information the Kiwix lib delivers, please let me know precisely the use case and we could discuss a way to allow that.

**Comment by kelson42** [comment]
I close that ticket as the grouping of ZIM files (by type/nature) should be done and can be dones AFAIK with tags.

**Comment by automactic** [comment]
What? No, the tags only have things like `_ftindex` and `novid`. The name has things like `kiwix.wikipedia_en_all`. None of these method is reliable for category. Some files have empty string in both `tags` and `name`. 

Take `3dprinting.stackexchange.com_en_all_2018-03.zim` for example. This file is newly created this March, it's tags =`_ftindex`, name = `''`

**Comment by automactic** [comment]
Yes, tags should not be a easy way to jam information into. The reason has been elaborated in #131. We should have a stand alone function to get category of a zim file.

**Comment by kelson42** [comment]
@automactic There is and wont be a category system in the ZIM file as there is not use case justifying it. #131 reports problems but nothing which justifies a category system IMO. Anyway, #131 will be discussed in #131 thread - not here.

**Comment by kelson42** [comment]
@automactic fixed

**Comment by rgaudin** [comment]
Please follow-up on [kiwix-tools#317](https://github.com/kiwix/kiwix-tools/issues/317)
