### ISSUE TITLE
Move kiwix-serve HTTP deamon primitives to kiwix-lib

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#138]
_From @kelson42 on December 30, 2016 21:16_

kiwix-serve binary should only rely on kiwix-lib and not on libmicrohttpd.

_Copied from original issue: kiwix/kiwix-tools#8_

**Comment by kelson42** [comment]
_From @mgautierfr on January 3, 2017 14:3_

For ctpp2 yes. libkiwix.pc should declare that it needs ctpp2 and it should just work.
But ctpp2 doesn't provide a pkg-config file, so we have to refind ourselves the dependency.
We have to provide a patch to ctpp2 do handle it (or at least have kiwix-builder create the libctpp2.pc file).

For libmicrohttpd, I'm not sure. libmicrohttpd is used only by kiwix-serve. I see no reason to this dependency in kiwix-lib.

**Comment by kelson42** [comment]
_From @legoktm on January 6, 2017 12:37_

Have we asked the ctpp2 upstream (<http://ctpp.havoc.ru/en/faq.html>) to provide a pkg-config file? If not, I think that would be a good idea.

**Comment by kelson42** [comment]
@mgautierfr What is exactly the status on this? I think ctpp2 is now in kiwix-lib and we have decided to keep libmicrohttps in kiwix-serve so far. What is also the point regarding @legoktm's question?

**Comment by kelson42** [comment]
kiwix-desktop 2.0 will include the HTTP server feature, so we will have to do it in the next months. For ctpp2, maybe would have a look to a replacment https://github.com/kiwix/kiwix-lib/issues/21.

**Comment by kelson42** [comment]
This is also necessary for https://github.com/kiwix/kiwix-android/issues/259

**Comment by kelson42** [comment]
@mgautierfr The reason why I want the HTTP daemon primitives in the kiwix-lib is that I want other ports of Kiwix to propose a web server. In particular Kiwix for Android.

**Comment by kelson42** [comment]
@mhutti1 It looks like we need that quite urgently meanwhile. Do you confirm? That said the implementation work can not be done in less than 2-3 weeks. Could we talk about the timeline?

**Comment by mhutti1** [comment]
If you want to email me/message me on slack that is fine but I am not directly looking at this project day to day, Abdul and Siddharth are.

**Comment by kelson42** [comment]
@abdulwd @siddharth2010 ?

**Comment by abdulwd** [comment]
@iadeelzafar will be needing it soon, I don't how far he can proceed without it. @iadeelzafar can you enlighten us on this?

**Comment by iadeelzafar** [comment]
@abdulwd @siddharth2010  We need to discuss a timeline for this and how we to move futher with kiwix-serve. @kelson42 has already told this in #android slack group. Discussion on the DNS jailing as well.

**Comment by kelson42** [comment]
@mgautierfr This is the prio 1 now to allow @iadeelzafar to finish implementation of Kiwix for Android Hotspot feature.

**Comment by kelson42** [comment]
@mgautierfr has still a few details to fix and we are good to close that ticket (and release libkiwix)

**Comment by kelson42** [comment]
This have been completed by @mgautierfr an will be part of next release.
