### ISSUE TITLE
Problem compiling kiwix-lib (with ctpp2)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#14]
On Ubuntu Xenial

$ meson ..
The Meson build system
Version: 0.29.0
Source dir: /home/kelson/kiwix-lib
Build dir: /home/kelson/kiwix-lib/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: kiwixlib
Native cpp compiler: c++ (gcc 5.4.0-6ubuntu1)
Dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency icu-i18n found: YES 55.1
Native dependency libzim found: YES 1.4
Native dependency pugixml found: YES 1.8
Program aria2c found: YES (/usr/bin/aria2c)
Has header "ctpp2/CTPP2Logger.hpp": YES

Meson encountered an error in file meson.build, line 24, column 2:
Unknown method "find_library" in object.

**Comment by legoktm** [comment]
I wonder if your meson version is too old? I've been using 0.37 from Debian Unstable which works fine.

https://github.com/mesonbuild/meson/wiki/Reference-manual#find_library doesn't say what version it was introduced in...

**Comment by mgautierfr** [comment]
This should be fixed with this last commit 317b13b

**Comment by kelson42** [comment]
@starmad Compiling dynamically works now, but not statically

```
$ meson --default-library=static . build
The Meson build system
Version: 0.37.1
Source dir: /home/kelson/kiwix-lib
Build dir: /home/kelson/kiwix-lib/build
Build type: native build
Project name: kiwixlib
Native cpp compiler: c++ (gcc 5.4.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency icu-i18n found: YES 55.1
Native dependency libzim found: YES 1.4
Native dependency pugixml found: YES 1.8
Has header "ctpp2/CTPP2Logger.hpp": YES

Meson encountered an error in file meson.build, line 26, column 4:
Cpp library 'ctpp2-st' not found

```

**Comment by kelson42** [comment]
The problem is that Ubuntu/Debian use libctpp2.a instalead of libtpp2-st.a

**Comment by kelson42** [comment]
Will try to fix it.

**Comment by kelson42** [comment]
fixed
