### ISSUE TITLE
Search Performance Issue

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-lib#146]
I have recently got a few complaints from kiwix for iOS user that search is very slow. So I did some time profiling. 

**Environment:**
- 5 zim files in total, some have embedded zim file some not. 
- The largest one is the 17GB+ Code7370 zim file. 
- Search text is "morristown". 
- `resultEnd` in `Searcher::search` is set to 20.
- freshly initialized reader objects 

The search operation takes 1.92s on my iPhone X. `kiwix::Result::get_snippet` alone takes 1.76s (91.4%) Here is the break down:

| Function                      | Time  | Time(%) |
|-------------------------------|-------|---------|
| zim::Article::getData         | 1.24s | 64.7    |
| Xapian::MSet::snippet         | 418ms | 21.7    |
| zim::myHtmlParser::parse_html | 92ms  | 4.7     |

-----------------

While I understand we are gonna do everything we can on libkiwix side. It would be a good idea to seek alternatives. 

One thought is to open API that allows a snippet to be generated by some other method. So I could show user results without snippet first, then asynchronously get the snippet (like as if they come from a WebAPI).

Another thought is to not to use `Xapian::MSet::snippet`, since I find the result often not very "clean". Maybe we could use the first sentence of an article as snippet and store it along with path of articles. But this is more a "how to improve snippet" problem. 

-----------------

Profiling screenshot:
<img width="698" alt="screenshot 2018-06-01 15 07 11" src="https://user-images.githubusercontent.com/8294252/40933541-c74cfdce-67ff-11e8-988f-b5599a677445.png">

**Comment by kelson42** [comment]
@mgautierfr What is your opinion on this? When do we exactly compute the snippets (for each fulltext search, for the suggestions)? I that an option to turnon? Would that be possible to provide a dedicated API call like suggested by @automactic

**Comment by automactic** [comment]
After some more thought, I think it might not be a good idea to get snippets after all results are presented to the user. Imagine a google search, how annoying it would be to see title of the results first and then content on the page move around because snippets are populated.

**Comment by kelson42** [comment]
@automactic This month all our Wikipedia ZIM files will be renewed using zstd as core compression solution. As a consequence, the decompression of an article is at least 5X time faster. On the top of this, in the last two libzim/libkiwix releases/builds, massive improvements have been done in read speed by implementing multiple/better cache and incremental cluster reading. Next libzim/libkiwix release will bring the last batch of improvements on this. This won't be the last speed improvements, but for the moment we think that the improvements are massive and enough for the moment and will stop investing on this.

I perfectly agree that snippets should be loadable asyncronously and want to do that for kiwix-serve as well.

**Comment by automactic** [comment]
@kelson42 thanks for the update!

**Comment by kelson42** [comment]
@automactic Here is the ticket about the snippet API https://github.com/kiwix/kiwix-lib/issues/395. Have you run new speed tests with ztsd based ZIM file? Like for example https://download.kiwix.org/zim/wikipedia/wikipedia_es_all_maxi_2020-11.zim. Does it makes sense to keep this ticket open?

**Comment by automactic** [comment]
No it does not make sense to keep this open. 

Frankly, I got around this issue by providing first paragraph and first sentence snippets. These snippets are retrieved in parallel utilize multi-cores of the CPU. (You should try it if you haven't) I personally don't find the xapian snippet that useful comparing to first sentence / paragraph

No I have not tried zstd based zim file, do you have a English version? I don't speak `es`

**Comment by kelson42** [comment]
@automactic WPEN max is still building, hopefully soon.
