### ISSUE TITLE
MIME: application/octet-stream on macOS

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-lib#153]
I rebuilt libkiwix with build https://github.com/kiwix/kiwix-lib/commit/0c26b08dcee5d9ce9fc580a813ef2f9050447e50 and its dependencies for both iOS and macOS. I have encountered a strange issue on macOS.

When loading an article, the MIME I get back from libkiwix sometimes is `application/octet-stream` with length 3. This issue only appears on macOS, also on both recent and old zim files. But not on iOS. It is also not random. Only some specific `Entry` has this problem and it is always reproducible. 

What could be the reason? It also could be something I have done wrong on the macOS side. But I can confirm this issue not appearing before I updated the libs.

**Example**:

wikipedia_en_all_novid_2018-05.zim
/A/Human_population.html

wikivoyage_en_all_2017-10.zim
/A/High_speed_train.html

**Comment by automactic** [comment]
What I feel strange is why this problem only exists on macOS build

**Comment by kelson42** [comment]
Sorry, we do not distribute `wikivoyage_en_all_2017-10.zim` but I have tested with the last version of Wikivoyage in English
```
$ zimdump -f Human_population.html -i /var/www/download.kiwix.org/zim/wikipedia/wikipedia_en_all_novid_2018-05.zim 
url: Human_population.html
	title:           Human population
	idx:             5803963
	namespace:       A
	type:            redirect
	redirect index:  13718156
$ zimdump -f High_speed_train.html -i /var/www/download.kiwix.org/zim/wikivoyage/wikivoyage_en_all_2018-06.zim 
url: High_speed_train.html
	title:           High speed train
	idx:             18119
	namespace:       A
	type:            redirect
	redirect index:  18097
```

@automactic Both examples are redirects. I'm not really sure why a redirect (so which should not be displayed) mime-type should play a big role...
@mgautierfr Redirects seem to have mime-types. But zimdump does not display it. How zimwriterfs does decide what is the mime-type for a redirect?

**Comment by automactic** [comment]
@kelson42 Ah, yes, I forgot to check redirection on Mac
