### ISSUE TITLE
searchSuggestionsSmart() does not fallback to legacy mode if broken FT index

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#154]
We have the problem on Android that ZIM files are splitted and therefore FT index broken. This is not a goal to keep that situation, but this is what we have for now under certain circumstances.

In that situation, the suggestion system is totally broken, which means that searchSuggestionsSmart() of the libkiwix does not return anything - always. To my opinion, it should still work with the legacy mode, the one we had before the Xapian index has been embedded in the ZIM files.

For example:
```
$ split --bytes=2M wikivoyage_en_all_nopic_2018-06.zim wikivoyage_en_all_nopic_2018-06.zim
$ rm wikivoyage_en_all_nopic_2018-06.zim
$ kiwix-search --suggestion wikivoyage_en_all_nopic_2018-06.zim Paris
$
```

I should see at least a result for the "Paris" article.

**Comment by kelson42** [comment]
MIght be the same as https://github.com/kiwix/kiwix-tools/issues/134

**Comment by mhutti1** [comment]
I believe this is fine on kiwix-android.

**Comment by kelson42** [comment]
We don’t recommend to split randomly ZIM files. Kiwix Android does not anymore. We have a proper zimsplit tools.
