### ISSUE TITLE
Build deb (for Debian repo)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#16]
This is the first step to then get the kiwix-tools.

**Comment by kelson42** [comment]
@legoktm Still motivated? You can contact "copyninja" on IRC which is the official Kiwix packager for Debian.

**Comment by legoktm** [comment]
Yep! I'm (slowly) working on it, currently fixing one of the dependencies - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849810

**Comment by kelson42** [comment]
@legoktm THX

**Comment by kelson42** [comment]
This is necessary to package kiwix-apache https://github.com/kiwix/kiwix-apache/issues/14

**Comment by kelson42** [comment]
@legoktm has announced that libkiwix is currently waiting for review in the Debian NEW queue - https://ftp-master.debian.org/new/libkiwix_0.2.0-1.html

**Comment by kelson42** [comment]
@legoktm Could we close that ticket?

**Comment by kelson42** [comment]
Seems not :( https://qa.debian.org/developer.php?login=legoktm%40member.fsf.org

**Comment by legoktm** [comment]
Two months later...libkiwix has been accepted into Debian! https://tracker.debian.org/pkg/libkiwix
