### ISSUE TITLE
Search suggestions doesn't work with MultiZIM

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-lib#160]
The old non full text search suggestions doesn't have any compatibility with multizim search. We could implement it on the Android side but it would be rather time consuming.

**Comment by kelson42** [comment]
@mhutti1 Is that the bug which is blocking for multizim support in Kiwix-Android?

**Comment by mhutti1** [comment]
Yes. All the things with this label are without significant hacky
workarounds.

**Comment by kelson42** [comment]
Duplicate of #479. Keeping the newest one as we have a bit more comments.
