### ISSUE TITLE
variable read

### ISSUE THREAD

**Issue by opk12** [kiwix/kiwix-lib#169]
`retVal` is read uninitialized in the `else` branch of [Reader::searchSuggestionsSmart](https://github.com/kiwix/kiwix-lib/blob/master/src/reader.cpp#L761):

    retVal = this->searchSuggestions(...) || retVal;

Possibly it should be set to false at the declaration site?

Found by cppcheck.

**Comment by kelson42** [comment]
@opk12 Would you be able to make a PR?

**Comment by mgautierfr** [comment]
Fixed by https://github.com/kiwix/kiwix-lib/commit/b996a2877c0082299f5934b73d462cca8b14cf34
