### ISSUE TITLE
Abbreviations cannot be searched anymore

### ISSUE THREAD

**Issue by Imarok** [kiwix/kiwix-lib#196]
I'm using Kiwix 2.2
Searching for abbreviations (like FFT) doesn't work anymore.
Some versions ago (2.1 or 1.97)  it worked properly.
Maybe refs #66 
(Maybe Disambiguation sites not working anymore is the underlying reason)

**Comment by mhutti1** [comment]
@kelson42 I didn't close this you did :P

**Comment by kelson42** [comment]
@mhutti1 You are right, sorry wrong move.
