### ISSUE TITLE
encountered an issue while compiling, reading no "mustache.hpp" header

### ISSUE THREAD

**Issue by JackalJohn** [kiwix/kiwix-lib#201]
Has header "mustache.hpp": NO 
meson.build:22:2: ERROR: Problem encountered: Cannot found header mustache.hpp

**Comment by mgautierfr** [comment]
You need the mustache dependency (https://github.com/kainjow/Mustache).
I've just update the README to mention it (#202)

**Comment by JackalJohn** [comment]
> You need the mustache dependency (https://github.com/kainjow/Mustache).
> I've just update the README to mention it (#202)

gosh..sorry for posting wrong place, thanks. 
I just began to touch Linux, so some of my issue may looks silly. 
I made it to run "meson . build"
but when I run "ninja -C build", this appeared.

![snipaste_2019 03 05 _01 08 48](https://user-images.githubusercontent.com/19181833/53749834-42c1b480-3ee3-11e9-957f-319e49709617.png)

**Comment by mgautierfr** [comment]
Arf, my bad, you need a patch for mustache.
I was certain I've send it upstream. See my recent PR here (kainjow/mustache#32)

**Comment by kelson42** [comment]
@mgautierfr @JackalJohn Can we do more her? Should we close the issue?

**Comment by JackalJohn** [comment]
sorry dute,  I've been too busy these months, just close it is fine, I'll tell ya when I meet new situations.




------------------ 原始邮件 ------------------
发件人: "Kelson"<notifications@github.com>; 
发送时间: 2019年5月4日(星期六) 上午10:32
收件人: "kiwix/kiwix-lib"<kiwix-lib@noreply.github.com>; 
抄送: "淳帅二代"<1292756898@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [kiwix/kiwix-lib] encountered an issue while compiling, readingno "mustache.hpp" header (#201)




@mgautierfr @JackalJohn Can we do more her? Should we close the issue?

**Comment by kelson42** [comment]
@JackalJohn Thx

**Comment by probonopd** [comment]
I am also running into this:

```
Dependency libcurl found: YES 7.47.0
Has header "mustache.hpp" : NO
meson.build:22:2: ERROR: Problem encountered: Cannot found header mustache.hpp
```

Here is my full build log:
https://api.travis-ci.com/v3/job/202605058/log.txt

Here is my Travis CI build script:
https://github.com/probonopd/kiwix-desktop/blob/897e903cef873ffb8ad736e2cc1872594d064f39/.travis.yml

`make install` does not work for Mustache:
https://github.com/kainjow/Mustache/issues/33

What can I do?

**Comment by samkellerhals** [comment]
@probonopd  I faced a similar issue. 

According to this [Stackoverflow Post](https://stackoverflow.com/questions/344317/where-does-gcc-look-for-c-and-c-header-files) you can use the following command to find out where your compiler is looking for header files ``gcc -print-prog-name=cc1plus` -v`, that is if you are on a Linux machine and using gcc as you compiler.

You can then simply copy the `mustache.hpp` file to the directory of header files. In my case this was `/usr/include`.

Then change into the kiwix-lib directory again and run `meson . build` then it should work!

Hope this helps.

**Comment by probonopd** [comment]
> You can then simply copy the mustache.hpp file to the directory of header files. In my case this was /usr/include.

That's what I am doing... no avail (unless I am doing it wrong)

https://github.com/probonopd/kiwix-desktop/commit/5d7477c5a89e57814ba20b74ec10e4bd38ad3efa

**Comment by mgautierfr** [comment]
Is it possible to have to full meson build log (/home/travis/build/probonopd/kiwix-desktop/kiwix-lib/build/meson-logs/meson-log.tx) ?

**Comment by probonopd** [comment]
https://api.travis-ci.com/v3/job/203345975/log.txt

**Comment by mgautierfr** [comment]
> travis_time:start:0df02ac8
[0K$ cp *.hpp /usr/include/
cp: cannot create regular file '/usr/include/catch.hpp': Permission denied
cp: cannot create regular file '/usr/include/mustache.hpp': Permission denied
travis_time:end:0df02ac8:start=1558975278936019784,finish=1558975278940967641,duration=4947857
[0K[31;1mThe command "cp *.hpp /usr/include/" exited with 1.[0m

**Comment by probonopd** [comment]
D'oh! Thanks @mgautierfr
