### ISSUE TITLE
pytest fail on Arch Linux

### ISSUE THREAD

**Issue by nobicycle** [kiwix/kiwix-lib#205]
Thank you for kiwix-lib
Compiling under Arch Linux:

> ==> Starting check()...
> [0/1] Running all tests.
> 1/6 cluster                                 OK       2.22 s 
> 2/6 dirent                                  OK       0.01 s 
> 3/6 header                                  OK       0.02 s 
> 4/6 uuid                                    OK       1.02 s 
> 5/6 template                                OK       0.01 s 
> 6/6 pytest                                  FAIL     0.62 s (exit status 1)
> 
Full log attached.

[testlog.txt](https://github.com/kiwix/kiwix-lib/files/2948098/testlog.txt)

**Comment by kelson42** [comment]
@mgautierfr Might you help us here?

**Comment by nobicycle** [comment]
Hi,
kiwix-lib 5.2.0 now compiles without error.
