### ISSUE TITLE
Create searcher with external index

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-lib#206]
Previously, we could create searcher by passing url to an external dir, like this `new kiwix::Searcher([idxDirURL fileSystemRepresentation])`

Now we no longer seems to be able to do so. https://github.com/kiwix/kiwix-lib/blob/master/include/searcher.h#L76

Question is: how do we support external search index?

**Comment by mgautierfr** [comment]
This feature has been removed.
See the commit https://github.com/kiwix/kiwix-lib/commit/5159d985c608074e1b6c34809bd286c4d829b0f4 and the discussion here : https://github.com/kiwix/kiwix-tools/issues/245
