### ISSUE TITLE
Provide a way to search within a geo square (not a circle)

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-lib#207]
Geo search: https://github.com/kiwix/kiwix-lib/blob/master/include/searcher.h#L119

The doc string is a bit French, so forgive me if I am misunderstanding. It sounds like the geo search is conducted on a circular region with radius, but I would imagine this is less useful than doing the search on a rect. Since the shape of our screens are in general a rect not a circle. 

If it is indeed a square, I would suggest changing it to a rect. In other words, a bounding box by providing min and max longitude and latitude.

**Comment by kelson42** [comment]
It is definitly a circle https://github.com/kiwix/kiwix-lib/blob/master/include/searcher.h#L114

**Comment by mgautierfr** [comment]
Yes, we are searching in a circle.
The main problem here is that xapian provide only a API to search for distance from a point shorter that a distance (ie, circle). There is no API to search in a square.

**Comment by mhutti1** [comment]
We could pretty easily use slightly larger circle and then some culling to search a box if it was particularly useful maybe?
