### ISSUE TITLE
Replacing ctpp2 by ctemplate HTML template engine

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#21]
ctpp2 seems to not been really maintained anymore (no release in 5 years) and is really not easy to use (complicated compilation scripts and needs to be patched).

It might be smartter to replace it. I have found a library which might be able to do the job:
https://github.com/olafvdspek/ctemplate

It's maintained and already packaged in Debian/Ubuntu

**Comment by kelson42** [comment]
@mgautierfr feedback?

**Comment by kelson42** [comment]
I do not see any pc file. See https://github.com/OlafvdSpek/ctemplate/issues/15#issuecomment-302651946

**Comment by kelson42** [comment]
@mgautierfr How much would you value the boost dependency? and the price of adding it?

**Comment by mgautierfr** [comment]
I think that boost could be a real win globally.
It is pretty easy to install (most of boost library are header only and it is the closest things we have from a standard).

There is a number of libraries that could be use in kiwix or libzim projects :
- [boost.filesystem](https://www.boost.org/doc/libs/1_69_0/libs/filesystem/doc/index.htm) to have os independent file manipulation.
- [boost.locale](https://www.boost.org/doc/libs/1_69_0/libs/locale/doc/html/index.html)  to handle localisation.
- [boost.process](https://www.boost.org/doc/libs/1_69_0/doc/html/process.html) (header only) and [boost.thread](https://www.boost.org/doc/libs/1_69_0/doc/html/thread.html) to create subprocess and threads os independently (for aria2, zimwriterfs, ...)
- [boost.uuid](https://www.boost.org/doc/libs/1_69_0/libs/uuid/doc/uuid.html) to generate uuid. (header only)
- [boost.asio](https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio.html) to do io (header only)
- [boost.beast](https://www.boost.org/doc/libs/1_69_0/libs/beast/doc/html/index.html) to do http request (and server) (pretty low level API) (header only)
- [boost.log](https://www.boost.org/doc/libs/1_69_0/libs/log/doc/html/index.html) to do some logging.
- [boost.test](https://www.boost.org/doc/libs/1_69_0/libs/test/doc/html/index.html) for unit testing. (header only)
- [boost.endian](https://www.boost.org/doc/libs/1_69_0/libs/endian/doc/index.html) to handle endianess. (header only)
- [boost.programOptions](https://www.boost.org/doc/libs/1_67_0/doc/html/program_options.html) to read options from command line or configuration file.

Of course we do not have to move to all those libraries in the same time (nor at all). We must evaluate pros and cons of each libraries and change if it is usefull.
But, all those libraries would potentially remove `ctpp2`, `libmicrohttpd`, `curl`, `googletest`; remove a lot of code in kiwix-lib and libzim about threading, filesystem operation, uuid, endian ... allow us to add the logging and localization features.

---

To come back on the subject, I think we can move to a templating using mustache (kainjow/Mustache).
It adds no dependency and if we decide to move `crow` after, the templating system is the same.

There is also this template system https://github.com/no1msd/mstch but it needs boost.

**Comment by kelson42** [comment]
@kelson42 Without having studied in details like you, my overall feeling is that `boost` is worth it now for the `kiwix-lib`. Regarding the templating system, I trust you to find something performant, maintained & well used, portable and relatively simple (also the txt template "language").

That said I'm pretty much against moving out from libmicrohttpd with an all-in-one solution because:
* I'm in general against all-in-one approach
* It is a lot of work to remove libmicrohhtpd, without clear added value for the users
* We have currently other priorities
* I was already thinking adopting https://github.com/nghttp2 (from Aria2 Tatsuhiro) later next year.
