### ISSUE TITLE
ReLinker should be used to load library

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-lib#239]
See [kiwix-android issue](https://github.com/kiwix/kiwix-android/issues/1259)

We should hopefully be able to reduce our crash rate by using [Relinker](https://github.com/KeepSafe/ReLinker)

**Comment by kelson42** [comment]
@macgills No sure exactly how this should be done, but I guess this something at the JNI level (Java? C++)?

**Comment by macgills** [comment]
this [line](https://github.com/kiwix/kiwix-lib/blob/93c404a952a798810f72020b01844649a2d4296b/src/android/org/kiwix/kiwixlib/JNIKiwix.java#L28) should be changed to `Relinker.loadLibrary("kiwix");`

**Comment by kelson42** [comment]
@macgills Good, seem easy. Then we should do it (and not forget to properly download the Java dependence too).

**Comment by macgills** [comment]
@mgautierfr 

```
2019-08-07 13:09:29.624 10488-10488/org.kiwix.kiwixmobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kiwix.kiwixmobile, PID: 10488
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/getkeepsafe/relinker/ReLinker;
        at org.kiwix.kiwixlib.JNIKiwix.<init>(JNIKiwix.java:30)
```
The relinker dependency is not included in the aar.
I believe that the dependency needs to be included in the pom file, I think the gradle solution would have supported this? I don't have the history of that anymore after a force push to get some example xml for the kiwix-build publishing code.

We could fix this temporarily by including reLinker in the android project but that is undesirable long term.

**Comment by mhutti1** [comment]
We should move  
https://github.com/kiwix/kiwix-build/blob/master/scripts/upload_kiwix_lib_android_to_bintray.py#L11 to kiwix-lib to allow us to specify dependencies.

Something like:

```
<dependencies>
  <dependency>
    <groupId>com.google.android</groupId>
    <artifactId>android</artifactId>
    <scope>provided</scope>
  </dependency>
</dependencies>```

Should work.

**Comment by kelson42** [comment]
@mgautierfr @macgills @mhutti1 What is the status here? Does the Android team expect something from @mgautierfr ?

**Comment by macgills** [comment]
On a new publication to bintray with the relinker dependency added to the pom I will update a PR and that will be the end of this ticket

**Comment by kelson42** [comment]
@macgills Would that be possible to do that PR now?

**Comment by macgills** [comment]
Relinker is now used, closing
