### ISSUE TITLE
Fix stopwords

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#26]
Stopwords are words which should not be indexed (during the FT index process) and also be ignore during the FT search. This stopwords are language specific. Lists are provided by Xapian and are at least used in zimwriterfs. This task is about to check that everything works fine on the indexing part but also on the reader side.

**Comment by kelson42** [comment]
@mgautierfr 

I have tested with the following file (create recently with last master version of libzim, libkiwix, kiwix-source and zimwriterfs): http://tmp.kiwix.org/wikipedia_fr_articles_2017-04.zim

If I search (using kiwix-serve) on "il " I get no result (even if the word "il" appears in many articles... so it works.

But if I search "le ", I get only "Londres" as result, which is strange because this words appears in all articles in because this is an obvious stop word it should appears nowhere.

Somethings looks to be wrong here.

**Comment by kelson42** [comment]
Another question: https://github.com/openzim/libzim/issues/12

**Comment by mgautierfr** [comment]
Seems to be a xapian bug will indexing (https://trac.xapian.org/ticket/750)

The "lea" of "lea valley" in the "Londres" article is stemmed to "le" but not stopped correctly.
