### ISSUE TITLE
Incompatibility with Mustache 4

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#264]
It seems the solution we have implemented to manage `urlencoded` does not work with Moustache4 (it takes the whole line up to the last carriage return) instead of only the content between
`{{#urlencoded}}` and `{{/urlencoded}}`. It looks like a bug in Mustache as this seems work fine with Mustache 3.2

**Comment by hashworks** [comment]
Related: https://github.com/kiwix/kiwix-tools/issues/321

**Comment by mgautierfr** [comment]
kainjow/Mustache 4 is still in beta. It may be a bug in mustache.

**Comment by kelson42** [comment]
@mgautierfr Could you please make a short bug report then? I don't have seen anything open,

**Comment by kelson42** [comment]
@mgautierfr Mustache 4 has been officially released https://github.com/kainjow/Mustache/commit/b1136d822e1d04dd111fb7bda4ca3adeb788ad8d. I tested it. The bug is still there unfortunately.

**Comment by mgautierfr** [comment]
Issue has already been opened there : https://github.com/kainjow/Mustache/issues/38

I'm afraid there is nothing we can do here (except fixing mustache itself)

**Comment by kelson42** [comment]
@mgautierfr No workarounds?

**Comment by mgautierfr** [comment]
I haven't found one. A workaround would be to simply move the `{{#urlencoded}}stuff{{/urlencoded}}` in its own line. But, in our case, as we use it inside a string, it would insert `\n` in the string and break the url.

A easiest solution is to stay on mustache 3

**Comment by kelson42** [comment]
Bug has been fixed now upstream. I don't see big value to keep this ticket open.
