### ISSUE TITLE
Better data directory for windows.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-lib#275]
For now, on windows, we are using the %APPDATA% environment variable as the directory to store the content.
By default it extends to `C:\Users\Username\AppData\Roaming`.

- It should be at least with a kiwix sub-directory (`%APPDATA%\kiwix`) as it is on linux.
- There is also the %LOCALAPPDATA% env var (`C:\Users\Username\AppData\Local`). I don't know what the difference between the intended use of those variable but maybe it better to use %LOCALAPPDATA%.
- Use something else ?

In any case, if we change the directory, we must at least explain that to the user as the library will appear empty (and we will not clear the content of the old directory). User should move the content from a directory to another.
And it could be a bit complex as aria2c may keep information about ongoing download using absolute path (I don't know, to check).

A script to do the migration could also be created. But it will only be used once and before the final release of kiwix-desktop is done (ideally, between rc2 and rc3). I'm not sure we want to do this for a pre-release.

@kelson42, what do you think about this?

**Comment by kelson42** [comment]
@mgautierfr Sounds good to me but if we change the location, we should move the files transparently and automatically. We need anyway this piece of code because we want to allow user to put their profile on an other custom location of their choice.
