### ISSUE TITLE
Kiwix does not support RFC8081 font mimetypes

### ISSUE THREAD

**Issue by rctgamer3** [kiwix/kiwix-lib#291]
As per [RFC 8081](https://tools.ietf.org/html/rfc8081), font mime types were standardised in 2017.

| extension |  mimetype |
|------------|-----------------|
otf | font/otf |
sfnt | font/sfnt |
ttf | font/ttf |
collection | font/collection |
woff | font/woff |
woff2 | font/woff2 |

I suggest adding support for these new mimetypes as listed [here](https://github.com/kiwix/kiwix-lib/blob/master/src/tools/pathTools.cpp#L393) (obviously only use the new ones that are relevant for use with Kiwix). However, you might want to add an if/else depending on your need for backwards compatibility with the old (now-deprecated) ones listed  below.

- application/font-sfnt
- application/x-truetype-font
- application/x-font-opentype
- application/vnd.ms-opentype

**Comment by kelson42** [comment]
@mgautierfr Why do we have this list here? My first impression is that we should have such a lib in the libkiwix?!

**Comment by mgautierfr** [comment]
The only place where we use this list is to define the mimetype of the embedded server content.
(The "skin" content).

We only have `css`, `js`, `png` and `gif`. So no need to extend the list for the font (in fact we should reduce it to only the 4 mimetype we have).

However, we should update the list in zimwriterfs (https://github.com/openzim/zimwriterfs/blob/master/src/tools.cpp#L46) as this list is used to detect the mimetype to store in created the zimfile.
(And maybe update the list in other tools as mwoffliner, if needed).
