### ISSUE TITLE
Case differentiation in search

### ISSUE THREAD

**Issue by beanandbean** [kiwix/kiwix-lib#296]
Book: Wiktionary English 2017-08-22

For Wiktionary, some uppercase alternatives of a word (which corresponds to distinct pages) do not appear in the search results. For example, among German uppercase nouns, "Leben" and "Kalender" work fine, but "Groß" or "Brot" do not appear.

**Comment by kelson42** [comment]
I confirm the bug. "Brot" and "brot" should give two different result. Thank you @beanandbean for reporting.
