### ISSUE TITLE
kiwix-serve des not run properly with libmicrohttpd 0.9.64 to 0.9.70 on macOS

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#324]
See https://bugs.gnunet.org/view.php?id=6090

**Comment by kelson42** [comment]
The bug has been fixed https://bugs.gnunet.org/view.php?id=6090. We need now a new libmicrohttpd release.

**Comment by rgaudin** [comment]
Version `0.9.71`, including the fix, has been released
