### ISSUE TITLE
To support video/audio files on Android the size of an asset should be readable from kiwixlib

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-lib#327]
As per this [Android issue](https://github.com/kiwix/kiwix-android/issues/1659) for the app to be able to ouput the correct data to the Webview we have to know its' size.

**Comment by mgautierfr** [comment]
There is no method especially made for this, but you can use `getContentPart` (https://github.com/kiwix/kiwix-lib/blob/master/src/wrapper/java/org/kiwix/kiwixlib/JNIKiwixReader.java#L70-L83). If you give a len of 0, `getContentPart` will set the size to the total size of the article.

**Comment by macgills** [comment]
Useful to know for experiments I'll be running.

`int len` <<< that is a bit worrying though in light of the recent offset problem, there may be videos in excess of 2GB,

**Comment by kelson42** [comment]
@mgautierfr @macgills I don't know if I should, but reading `JNIKiwixInt` for a size... is that not forseen that we will have problem with size > 4GB due to `int` size limitation?

**Comment by macgills** [comment]
Yes and the limitation is 2GB because of java signed ints, I don't know how many video files >2GB there are so I don't know the practical effect but I assume we will be extending `getDirectAccessInformation` to contain the necessary information ie size as a long. Currently the android app does not use `getContentPart` and my assumption is I won't push anything to production that does use it

**Comment by kelson42** [comment]
@macgills It has been confirmed that implementing this ticket would solve problems with audio/video content on Android. So quite important ticket.

**Comment by kelson42** [comment]
@mgautierfr This is quite urgent this feature is part of the libkiwix, so we can fix Kiwix Android.
