### ISSUE TITLE
getArticleCount and getMediaCount return very huge number when these info does not exist in OPDS

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-lib#333]
I don't think we current report article and media count in OPDS xmls. However, when calling `book->getArticleCount()` and `book->getMediaCount())`, very huge numbers are returned.

Example: 
```
printf("id: %s, article count: %llu, media count: %llu \n", _book->getId().c_str(), _book->getArticleCount(), _book->getMediaCount());

Outputs: id: 250c0b22-3cfe-e300-ad0f-53b1ffe09c70, article count: 4364093994, media count: 6132376528
```

I don't know if we are ready for c++ 17, but it would be great if those field could return `std::optional<u_int64>` in the absence of these fields

**Comment by kelson42** [comment]
@automactic Thank you, we need to fix that quickly.
