### ISSUE TITLE
CrashReport Android 3.3.1 Lib 9.1.2: signal 7 (SIGBUS), code 2 (BUS_ADRERR) zim::Fileheader::read(std::shared_ptr<zim::Buffer const>)

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-lib#361]
```
backtrace:

 
  #00  pc 00000000003b5438  /data/app/org.kiwix.kiwixmobile-iZyIK6oikc6K7TLGoYd-xQ==/base.apk (offset 0x685000) (zim::Fileheader::read(std::shared_ptr<zim::Buffer const>)+60)

 
  #01  pc 0000000000397384  /data/app/org.kiwix.kiwixmobile-iZyIK6oikc6K7TLGoYd-xQ==/base.apk (offset 0x685000) (zim::FileImpl::FileImpl(std::string const&)+908)

 
  #02  pc 000000000039454c  /data/app/org.kiwix.kiwixmobile-iZyIK6oikc6K7TLGoYd-xQ==/base.apk (offset 0x685000) (zim::File::File(std::string const&)+36)

 
  #03  pc 0000000000179f2c  /data/app/org.kiwix.kiwixmobile-iZyIK6oikc6K7TLGoYd-xQ==/base.apk (offset 0x685000) (kiwix::Reader::Reader(std::string)+144)

 
  #04  pc 00000000001bd10c  /data/app/org.kiwix.kiwixmobile-iZyIK6oikc6K7TLGoYd-xQ==/base.apk (offset 0x685000) (Java_org_kiwix_kiwixlib_JNIKiwixReader_getNativeReader+172)

 
  #05  pc 0000000000002a48  /data/app/org.kiwix.kiwixmobile-iZyIK6oikc6K7TLGoYd-xQ==/oat/arm64/base.odex (offset 0x1b000)
```

**Comment by mgautierfr** [comment]
Do you know which file you were trying to read ?
If kiwix-android has downloaded it, do you know if the download was complete ?

**Comment by macgills** [comment]
I am afraid I have no information. This is from a google crash report.

Kiwix-Android has a feature to prevent downloads initiated by it from being read during the download and to the best of my knowledge it is working fine. Perhaps a heavily non performant device could be at play.

If this exception could be bubbled up to java I can just abandon reading the file, if that is an option

**Comment by kelson42** [comment]
@mgautierfr Should we consider this problem has symptomatic to the corrupted ZIM files we have published?

**Comment by mgautierfr** [comment]
Without further information yes.

And now libzim raises an exception instead of exiting (https://github.com/openzim/libzim/commit/f5e3c3a4fc3d1b3d5eef12fbc7213b616bf0a5e4). (But I've made nothing but this change. I don't know if the exception is bubbled up correctly or catch before).
