### ISSUE TITLE
kiwix-lib on ubuntu16.04   Run-time dependency libzim found: NO (tried pkgconfig and cmake)

### ISSUE THREAD

**Issue by wjyuu** [kiwix/kiwix-lib#370]
hi，
i have a question for kiwix-lib on ubuntu16.04.
Once all dependencies are installed, i compile the Kiwix library with:meson . build
***************************************************************************************************************************
123@ubuntu:~/work/kiwix-lib-master/kiwix-lib-master$ meson . build
The Meson build system
Version: 0.52.1
Source dir: /home/123/work/kiwix-lib-master/kiwix-lib-master
Build dir: /home/123/work/kiwix-lib-master/kiwix-lib-master/build
Build type: native build
Project name: kiwix-lib
Project version: 9.2.2
C++ compiler for the host machine: ccache c++ (gcc 5.4.0 "c++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609")
C++ linker for the host machine: GNU ld.bfd 2.26.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Run-time dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency icu-i18n found: YES 55.1
Found CMake: /usr/bin/cmake (3.5.1)
Run-time dependency libzim found: NO (tried pkgconfig and cmake)

**Comment by kelson42** [comment]
You don't have installed, or installed wrongly the libzim.

**Comment by wjyuu** [comment]
> 您尚未安装libzim或安装错误。

sudo apt-get install libzim-dev

**Comment by wjyuu** [comment]
> You don't have installed, or installed wrongly the libzim.
************************************************************
123@ubuntu:~/work$ sudo apt-get install libzim-dev
[sudo] password for 123: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libzim-dev is already the newest version (1.2-9).
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.
*************************************************************

**Comment by kelson42** [comment]
From the `README.md`

```
These dependencies may or may not be packaged by your operating
system. They may also be packaged but only in an older version. The
compilation script will tell you if one of them is missing or too old.
In the worse case, you will have to download and compile bleeding edge
version by hand.
```

This is the reason probably of your problem.

**Comment by wjyuu** [comment]
Do you know how to compile libzim-dev?
I tried. There were many mistakes.
I don't know if it's the wrong way.

**Comment by mgautierfr** [comment]
Have you tried using https://github.com/kiwix/kiwix-build ?

**Comment by wjyuu** [comment]
> Have you tried using https://github.com/kiwix/kiwix-build ?

Yes, I tried this tutorial.
I arrived at this step：kiwix-build kiwix-lib # will build kiwix-build and its dependencies
And there are no errors in the compilation.
I went on to the next step：kiwix-build --target-platform native_dyn
Compilation complete，no error.
but,I don't know what to do next.
Did I do it right?
Can you tell me what to do next?
thanks！！！！

**Comment by mgautierfr** [comment]
If there is no error in the compilation step, it means that every thing is ok.

The kiwix-lib binaries (and other) are in `BUILD_native_dyn/INSTALL`

**Comment by wjyuu** [comment]
> If there is no error in the compilation step, it means that every thing is ok.
> 
> The kiwix-lib binaries (and other) are in `BUILD_native_dyn/INSTALL`

thanks，
How can I use this library next？
There are five folders in it. Which one is it?
How do I use these binaries?
I'm a novice. There are many things I don't know. Please forgive me.thanks

**Comment by mgautierfr** [comment]
If you want to build kiwix-tools, the command is `kiwix-build kiwix-tools`.
It will build kiwix-tools project and install the binaries in `BUILD_native_dyn/INSTALL/bin`.

If you want to move/copy the `kiwix-serve`, it is easier to build kiwix-tools statically (and so include the libraries in the binary) : `kiwix-build kiwix-tools --target-platform native_static`
Then it will install `kiwix-serve` in `BUILD_native_static/INSTALL/bin`, you can copy it where you want to use it.

It worth to mention that we are publishing a build version of kiwix-tools in https://download.kiwix.org/release/kiwix-tools/ for the release and https://download.kiwix.org/nightly/ every night with the head version of all the projects.

**Comment by wjyuu** [comment]
> If you want to build kiwix-tools, the command is `kiwix-build kiwix-tools`.
> It will build kiwix-tools project and install the binaries in `BUILD_native_dyn/INSTALL/bin`.
> 
> If you want to move/copy the `kiwix-serve`, it is easier to build kiwix-tools statically (and so include the libraries in the binary) : `kiwix-build kiwix-tools --target-platform native_static`
> Then it will install `kiwix-serve` in `BUILD_native_static/INSTALL/bin`, you can copy it where you want to use it.
> 
> It worth to mention that we are publishing a build version of kiwix-tools in https://download.kiwix.org/release/kiwix-tools/ for the release and https://download.kiwix.org/nightly/ every night with the head version of all the projects.

Thank you. You solved my problem！Thank you very much.   :-)
