### ISSUE TITLE
test timeout on slow architectures

### ISSUE THREAD

**Issue by LocutusOfBorg** [kiwix/kiwix-lib#375]
Hello, looks like 30 seconds for server testing is really not enough to make the testsuite pass on emulated hardware such as qemu-riscv64
https://launchpadlibrarian.net/487000588/buildlog_ubuntu-groovy-riscv64.libkiwix_9.2.2+dfsg-3_BUILDING.txt.gz

Can you please increase a little bit the timeouts?

**Comment by kelson42** [comment]
@LocutusOfBorg Seems legit. If you have a PR I would merge it.

**Comment by legoktm** [comment]
I'll bump the timeout to 300 seconds in my next Debian upload, if that goes well we can merge it in kiwix-lib?

**Comment by mgautierfr** [comment]
300 seconds is 5 minutes. I don't want to wait for 5 minutes is there is something wrong in my change.
Timeout is for something. If you know that you are testing on a small architecture, you can extend the timeout at run time with `-t` option. (As said in https://github.com/openzim/libzim/pull/361)

We may extend a bit the timeout but multiply it by 10 by default is probably too much.

**Comment by legoktm** [comment]
That's fair. I think setting it to something that is for sure high enough is OK for our packaging purposes to at least see how long these slower architectures need, and then determining whether it makes sense to bump the default or whether we want distributors to to keep a higher timeout on our side.

**Comment by LocutusOfBorg** [comment]
Hello, this is on emulated riscv64:

```
[0/1] Running all tests.
 1/10 parseUrl    OK             0.77s
 2/10 library     OK             0.92s
 3/10 regex       OK             0.89s
 4/10 tagParsing  OK             0.47s
 5/10 stringTools OK             0.75s
 6/10 pathTools   OK             0.82s
 7/10 kiwixserve  OK             0.42s
 8/10 book        OK             0.86s
 9/10 manager     OK             1.03s
10/10 server      OK             97.26s

Ok:                 10  
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   
```

So, maybe 150-200 is a value that makes everybody happy?

**Comment by LocutusOfBorg** [comment]
This is the new version 9.3.0
```
 1/10 parseUrl    OK             1.01s
 2/10 library     OK             1.00s
 3/10 regex       OK             1.14s
 4/10 tagParsing  OK             1.13s
 5/10 stringTools OK             0.98s
 6/10 pathTools   OK             0.83s
 7/10 kiwixserve  OK             0.60s
 8/10 book        OK             0.63s
 9/10 manager     OK             1.09s
10/10 server      OK             146.04s

Ok:                 10  
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   
```

**Comment by LocutusOfBorg** [comment]
thanks!
