### ISSUE TITLE
Use werror=true for CI only

### ISSUE THREAD

**Issue by Artoria2e5** [kiwix/kiwix-lib#390]
It is a terrible idea to use `-Werror` in production, as there is no guarantee what future compilers will do with regards to default error levels. A [quick search on GitHub](https://github.com/search?q=Werror&type=Issues) would reveal how much mess this seemingly careful behavior has caused. `-Werror` is for CIs, not for deployments that just need to work.

I think this can be done by removing `werror=true` from the meson file and adding `--werror=true` on the CI command-line, but I am really unfamiliar with this thing.

**Comment by Artoria2e5** [comment]
Looks like kiwix-tools has the same issue too.

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan Any feedbacl on this? You agree?

**Comment by veloman-yunkan** [comment]
@kelson42 I don't have any strong objections.

**Comment by kelson42** [comment]
@Artoria2e5 Would you be able to make a PR which implements a fix?

**Comment by kelson42** [comment]
I had a look in detail to this issue and will close it as WONTFIX:
* We don't have a concrete problem
* I want to have a strict compilation of the code (so no warning)
* If we have new errors with new compilers, then this means our code is "weak" and we have to fix the warnings. Having a strong error is the best manner to do it.
