### ISSUE TITLE
Prevent taskbar at article-level

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-lib#391]
In the context of zimit we need to be able to query HTML article and retrieve them as is, without the taskbar.
In current zimit, we have the JS replayer query articles and displaying them itself.

In the current libkiwix, the taskbar can only be disabled globally at the library caller level (kiwix-serve in this case) and if enabled, automatically applies to all `text/html` articles.

It used to be fine with other scraper as the typical use case is to retrieve JSON or JS data from other URLs but in this case, the replayer requests full HTML content and so the taskbar is injected where it doesn't belong.

This is currently circumvented by storing those HTML articles with a different MIME-type.

**Question**: what is the wanted behavior for this? Should we be able to request raw content? Is the mime-trick the way to go? Is there anything in this field in libzim2?

@mgautierfr @kelson42 @ikreymer

**Comment by ikreymer** [comment]
I don't have a particular preference, as long as it is possible to retrieve the raw content. Since the headers are stored in the `H/...` record, the Content-Type is read from there, so the mimetype in the `A/...` record is not used for the replay itself.

**Comment by kelson42** [comment]
Interesting ticket. For the moment I'm a bit dry with good ideas. Hopefully @mgautierfr has a genius idea.

**Comment by mgautierfr** [comment]
I have no genius idea here.

- We still want to include the taskbar on the "main" page (the replayer) but not on all other content.
- And this only for few zim files. For other zim files, we still need to include the taskbar all the time.

The only solution I see for now is #392. It would not be kiwix-lib inserting the taskbar but the zim article itself. So each zim would be able to do as it wishes.

**Comment by kelson42** [comment]
> In the context of zimit we need to be able to query HTML article and retrieve them as is, without the taskbar.
> In current zimit, we have the JS replayer query articles and displaying them itself.

What is exactly the problem we have currently? because the taskbar should be displayed anyway!

**Comment by kelson42** [comment]
I believe the best solution is that the kiwix-serve provides an api to get the content raw.

An other solution would be that if the mime-type parameter `Partial=true`, then the kiwix-serve will skip the taskbar introduction.

**Comment by rgaudin** [comment]
> I believe the best solution is that the kiwix-serve provides an api to get the content raw.
> 
> An other acceptable solution would be that if the mime-type parameter `Partial=true`, then the kiwix-serve will skip the taskbar introduction.

Strongly support having this capability. Not sure about best approach to implement it though.
