### ISSUE TITLE
Feature Request - Status code for no search results

### ISSUE THREAD

**Issue by darkenvy** [kiwix/kiwix-lib#393]
When searching, everything is returned as a 200 OK. 
In the event that no results are shown (such as reaching past the last page), we should return a 204 No Content.

**Why 204?** 
The server performed it's task correctly, there is simply nothing to show. 404 would work as well, but may indicate a more severe error when there isn't one.

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Why is this helpful?**
* Scripts that test the integrity of zims can benefit from status codes (in general).
* We are taking advantage of the fact that zims are indexed. We are using this to scrape articles names on search terms for future zim creation. Having a status code helps stop the script when it reaches a 204 status code.

**Priority**: Low

![https://puu.sh/yoL2g/950f20c666.png](https://puu.sh/yoL2g/950f20c666.png)

**Comment by MananJethwani** [comment]
can I work on this?

**Comment by kelson42** [comment]
@MananJethwani yes

**Comment by MananJethwani** [comment]
basically what I am doing is just checking before returning that if response content is empty then change the status code......is this fine or should some other changes must be included?

**Comment by kelson42** [comment]
no, you should check if the search returns result and change the status code if not.

**Comment by MananJethwani** [comment]
should I make changes in test/server.cpp as well? as it would fail if 204 is returned when it expects 200 status code

**Comment by kelson42** [comment]
@MananJethwani Please do a PR which secures that what is asked in the ticket is implemented. We would then review it and ask for changes if needed.

**Comment by kelson42** [comment]
FYI, we might have to rollback the fix of this ticket because it creates new problem, see #466
