### ISSUE TITLE
Delete Xapian indexer code from kiwix-lib

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#4]
It's useless meanwhile

**Comment by mgautierfr** [comment]
Xapian indexer code is used in kiwix-install, kiwix-index and the component zimXapianIndexer.
So it is used by two repository kiwix-tools and (the futur version of) kiwix.

I think it is better to keep it kiwix-lib. Or are you thinking of dropping indexing from kiwix as we are moving to zim files with embedded index ?

**Comment by kelson42** [comment]
@mgautierfr If we keep it, wee need to share the code with the zimwriterfs.

**Comment by mgautierfr** [comment]
At the end yes. But as long as we still provide zim with separated index (so without index), I think you should keep them.
As soon as all our kiwix versions handle zim+embedded index, those tools will become useless and we will remove them.

**Comment by kelson42** [comment]
@mgautierfr OK, so decison has been made to remove them as we can anytime recompile the old code and binaries are already provided. Maintaining two indexing solution is a burden.

**Comment by kelson42** [comment]
@mgautierfr You confirm this has been done?

**Comment by mgautierfr** [comment]
Indexer has been removed from `kiwix-lib` yes.

All the code has moved to `libzim`.
But I've keep some xapian code in `kiwix-lib` to be able to handle old fulltext database (separated from the zim)
