### ISSUE TITLE
Block external link feature doesn't work with root prefix.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-lib#407]
The "block external link" feature doesn't take into account the root prefix at all.

### How to reproduce

Run `kiwix-serve -p 8000 foo.zim -b -r ROOT` then go to `http://localhost:8000/ROOT/foo` and click on a external link.

**Comment by MananJethwani** [comment]
@kelson42 @mgautierfr can I work on this issue?

**Comment by kelson42** [comment]
@MananJethwani yes
