### ISSUE TITLE
kiwix-lib on ubuntu 20.04 Run-time dependency libzim is not upto required version >=6.1.8

### ISSUE THREAD

**Issue by i-rebel-aj** [kiwix/kiwix-lib#414]
Hi there!
while compiling libzim using `meson . build`,  I get the following error

Dependency` libzim found: NO found 4.0.4 but need: '>=6.1.8'

I checked the following link
https://pkgs.org/download/libzim-dev

libzim 6.2.0 is available only for ubuntu 20.04

I modified [meson.build ](https://github.com/kiwix/kiwix-lib/blob/master/meson.build) file line 28 to:-

`libzim_dep = dependency('libzim', static:static_deps)`

the build was success, so **is there a possibilty on removing version check on libzim dependency to make build possible with lower versions of ubuntu?**

**Comment by mgautierfr** [comment]
There is a lot of change and bug fix between 4.0.4 and 6.2.0.
kiwix-lib may compile with old version of libzim (and this is by chance here as the api breaks are about the writer part, not used by kiwix-lib) but a lot of feature will not work correctly.

If libzim is not packaged for you distribution, you have to compile it yourself.
