### ISSUE TITLE
Kiwix-serve content/counter intepretation broken with mime-type using extended attributes

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#416]
If `M/Counter` looks like this:
```
application/javascript=8;text/html=3;application/warc-headers=28364;text/html;raw=true=6336;text/css=47;text/javascript=98;image/png=968;image/webp=24;application/json=3694;image/gif=10274;image/jpeg=1582;font/woff2=25;text/plain=284;application/atom+xml=247;application/x-www-form-urlencoded=9;video/mp4=9;application/x-javascript=7;application/xml=1;image/svg+xml=5
```

Then we get in Kiwix serve:
![image](https://user-images.githubusercontent.com/1029718/97273817-18e5a000-1834-11eb-976e-afbf8df814b4.png)

We say there is only 3 articles, but actually there is far more activles.

I believe the problem is at least that `text/html;raw=true=6336;` is not parsed properly.

This impacts all new Zimit created ZIM files.

**Comment by kelson42** [comment]
@mgautierfr If you could briefly fix that one, that would be helpful.

**Comment by mgautierfr** [comment]
I will do. But I'm not sure we should (or just stop here).

The `raw=true` means that the reading must not add ui around (in) the content.
It globally means that it will we include in "something" else and so it is not an article.

It make sense to count it in the context of zimit with the webreplay system but only in this context.

We should base ourselves on another information.
I propose to use the hint (https://github.com/openzim/libzim/blob/libzim_next/include/zim/writer/item.h#L121) of the next libzim api. This will allow the creator to tell if a entry is an article (or a media) whatever is the mimetype.

**Comment by kelson42** [comment]
OK, but the `M/Counter` parser is still wrong IMO.

**Comment by mgautierfr** [comment]
The `M/Counter` count the number of entries per mimetype.
This is arguable but for me, `text/html` is different than `text/html;raw=true`. Merging both is a lost of information.
If we have to merge them, it is at reading we should do it.

**Comment by kelson42** [comment]
@mgautierfr I believe I was unclear. The code looks at the first `=` for the separator. I believe it should take the last one `=`.

**Comment by mgautierfr** [comment]
My bad, I've missed the `parser` in your comment.
