### ISSUE TITLE
Reverse API onload() callback (ZIM -> Reader)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#443]
In #322,  @mgautierfr made the folloging comment:

Inserting before `</head>` (so just before the end of the `<head>` tag) should keep everything in the head at the beginning of the file.

---

However, this issue makes me think about another way we could use to include the taskbar in the content. We could use a small js file in every article to modify the dom. This small (or not) script would always be the same name, a wellknown name (ie, `/clientScript.js` or something like that). Even if all articles in the zim file would try to include it, it would be not in the zim file, but provided by the client (kiwix-tools, android, macos, desktop client, ...). It would be to the js to modify the dom to add the taskbar, do ask for suggestions and so.

I see several pros for this:
- If we add the script tag in the html directly, we don't have to modify the html on the server to include the taskbar.
- The js/css would be cached by the browser, instead of being download several times (embedded in the html)
- The js could do more than add the taskbar, on native client, it could be use to parse the html, generate a table of content and send it to the native code using the appropriate way.
- Vendors, who already proxy kiwix-serve, could intercept the request to the js and provide their own. This way, they could use custom css, button, ... to integrate correctly with their system.

The main cons I see is that we need js compatible browser. This is the case for most of the browser in the market but some vendors may use
pretty old browser or specific device that doesn't support js (I'm thinking about reader/tablet). We should see with them if this is a blocker or not (@tim-moody, @letompouce, other...)

**Comment by kelson42** [comment]
@rgaudin's reaction


I also think @mgautierfr's suggestion is good. It would add a lot of flexibility and could foster contributions to this part which has received many requests over the years but is currently not that easy to hack on.

I'm not in favor of dropping no-js support though ; so that would mean injecting content to the page anyway…

* display the HTML-only part (what's currently in `body .kiwix`) of the taskbar (or even a simplified version) in a `<noscript />` tag.
* display a link plus css code hiding main content inside a `<noscript />` tag. the link would lead to that same page but letting libkiwix know it should include an oldstyle taskbark.

Not in favor of the latter as it would mean two different URLs for the same content.

What I don't like about any version is that it means two different ways to render the taskbar with one that we'll always forget to test and probably break.

**Comment by letompouce** [comment]
On our side, I think we dropped the no-JS support at some point.

**Comment by kelson42** [comment]
> * If we add the script tag in the html directly, we don't have to modify the html on the server to include the taskbar.

We will do, it will just be only in js and not in C++.

> * The js/css would be cached by the browser, instead of being download several times (embedded in the html)

We should make this piece of HTML in external resources, and then this pb is fixed. All in one it does not play a role as the inserted HTML is so small. See #444.

> * The js could do more than add the taskbar, on native client, it could be use to parse the html, generate a table of content and send it to the native code using the appropriate way.

We can do that already if necessary. TOC should be make available on demand via JS API (see MWoffliner PR https://github.com/openzim/mwoffliner/pull/1237).

> * Vendors, who already proxy kiwix-serve, could intercept the request to the js and provide their own. This way, they could use custom css, button, ... to integrate correctly with their system.

This is a flexibility which would be good to provide, but for that we can simply create a URL to access this javascript/css in place of just inserting it. See #444.

After thinking twice about it I'm not in favour of implementing such a reverse API, this put and additional constraint on all ZIM makers for almost not added value for the end-user.

**Comment by kelson42** [comment]
Closing for now, no real problem to solve anymore and no consensus on the approach.
