### ISSUE TITLE
git master head is not able to read properly older pokepedia ZIM file

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#447]
None of the cutting edge kiwix-manage, kiwix-serve or even kiwix-desktop is able to read https://download.kiwix.org/zim/other/pokepedia_fr_all_nopic_2019-05.zim but zim-tools can. It works fine with latest release of Kiwix Desktop. I strongly suspect a regression has been introduced at the libkiwix level.

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan Any ideas, we probably better explain this problem before next libkiwix release.

**Comment by mgautierfr** [comment]
The zim file has no `Counter` metadata.
kiwix-lib should handle that (I've a fix) but it would be nice to also fix the writer (or not, I think we should make the counter mandatory and create it at libzim level. But for now we need it in the scrapper).
