### ISSUE TITLE
Kiwix-serve suggestions does return terms which are not title

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#45]
Kiwix-serve suggestions should only return title of articles. This looks like a regression added by the search engine rewriting.

**Comment by mgautierfr** [comment]
@kelson42, have you a reproducer ? Which terme had you search on which zim file ?

I've tried with wikipedia_fr and it seems that only titles are suggested.
On the code side, the suggestion system only work on titles so it should return titles only.

**Comment by kelson42** [comment]
I can not reproduce it, will reopen it if necessary.
