### ISSUE TITLE
ABI break in kiwix::split

### ISSUE THREAD

**Issue by ericonr** [kiwix/kiwix-lib#454]
https://github.com/kiwix/kiwix-lib/commit/08464f23bc0756fc99e2e1559f95d325f52fba87 introduced an ABI breakage by adding another parameter to `kiwix::split`.

This broke kiwix-tools' `kiwix-serve`, which was built with a previous version of kiwix-lib, and was using the `_ZN5kiwix5splitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_b` symbol, not the new `_ZN5kiwix5splitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_bb` symbol exported by `libkiwix.so.9`, which replaced the old one completely.

**Comment by kelson42** [comment]
@ericonr kiwix-tools git master compiles properly againsts libkiwix git master. Use `ldconfig`, refresh your git or secure you don't use an other vertsion of libkiwix.

**Comment by mgautierfr** [comment]
This is a ABI break yes. I missed this. Sorry.
Next version will have a API/ABI break and we will bump the major version.
