### ISSUE TITLE
kiwix::Manager's readXml() and readOpds() methods modify their read-only input parameter

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/kiwix-lib#462]
Usage of `pugi::xml_document::load_buffer_inplace()` in `kiwix::Manager::readXml()` results in the modification of its `const std::string& xml` parameter.

https://github.com/kiwix/kiwix-lib/blob/0586ef6d41ca24eabb84973fd67f72ed6ac5a227/src/manager.cpp#L76-L90

`kiwix::Manager::readOpds()` is faulty in the same way:

https://github.com/kiwix/kiwix-lib/blob/0586ef6d41ca24eabb84973fd67f72ed6ac5a227/src/manager.cpp#L123-L135

**Comment by kelson42** [comment]
@veloman-yunkan what is the impact?

**Comment by veloman-yunkan** [comment]
I am not aware of any current impact. But since `kiwix::Manager::readXml()` is part of the public API of libkiwix it shouldn't behave in such a nasty way. The fix is trivial.
