### ISSUE TITLE
Wrong handling of zero result in fulltext search

### ISSUE THREAD

**Issue by soumyankar** [kiwix/kiwix-lib#466]
The search function doesn't exactly work when made to search for keywords that doesn't exist in the book and the library.
To recreate the bug:
1. Download this [zim file](https://download.kiwix.org/zim/wikipedia_en_100_maxi.zim) (However, you can do this with any other zim file)
2. Search for "Charlie" and you will find results.
3. Search for "Angelina Jolie" and page refreshes with no change.
4. Force search by creating a new tab and typing in the following URL: 
http://localhost/search?content=wikipedia_en_100_maxi_2021-02&pattern=Angelina+Jolie

Weird behaviour where the page doesn't redirect anywhere and also the URL disappears(On macOS/Safari). For a better view into the bug, I recorded my screen and attached it here.

https://user-images.githubusercontent.com/10772786/111436425-f9d6a480-8727-11eb-9e96-4fb31039e78a.mov

**Comment by MananJethwani** [comment]
@kelson42 I faced a similar issue
http://library.kiwix.org/search?content=wikipedia_lt_all_mini_2021-02&pattern=%2F+
why doesn't url like these work?
like if you go to http://library.kiwix.org/wikipedia_lt_all_mini_2021-02/A/Pagrindinis_puslapis
and search for /  autocomplete shows one option with / but the option containing '/'..  doesn't work

**Comment by kelson42** [comment]
I confirm the bug, not clue why this fails. Serious bug!

**Comment by MananJethwani** [comment]
@kelson42 I suppose this might be a bug related to `libzim` while storing in `xapian::database` when I try to print `database.get_metadata("valuesmap")`
even with 1 title I get this as output `title:0;wordcount:1;geo.position:2`.

**Comment by kelson42** [comment]
@mgautierfr @maneeshpm Any idea?

**Comment by maneeshpm** [comment]
> @kelson42 I suppose this might be a bug related to `libzim` while storing in `xapian::database` when I try to print `database.get_metadata("valuesmap")`
> even with 1 title I get this as output `title:0;wordcount:1;geo.position:2`.

The metadata `valuesmap` stores the slot number of various parameters. Here, `title:0;wordcount:1;geo.position:2` means that we are storing titles in the slot number 0, wordcount in slot number 1 and so on. This does not signify the number of titles.

As far as libzim is concerned, when we don't have any matching document we do not throw any exception of sorts that can cause such an issue. Rather, an empty iterable search result is returned. I think I should have a look at the implementation of search in kiwix-lib.

**Comment by kelson42** [comment]
@maneeshpm Ok, the the problem is in the handling of zero resukt. I guess that an other symptom of the same bug is that this URL does not display anything http://library.kiwix.org/search?content=wikipedia_en_100_maxi&pattern=Angelina+jolie

**Comment by maneeshpm** [comment]
@kelson42 I agree. We should review the implementation of empty result handling.

**Comment by maneeshpm** [comment]
This issue is arising because of the status code `MHD_HTTP_NO_CONTENT` (204). In the `handle_search()` subroutine,
```c++
    if(searcher.getEstimatedResultCount() == 0)
    {
      response->set_code(MHD_HTTP_NO_CONTENT);
    }
```
If the status code is replaced with anything else (200, 404, 501 etc), we get the expected behavior and get a "no search results found" screen. I could not find any custom handling for `MHD_HTTP_NO_CONTENT` in the kiwix code either. I am not sure, but afaik this status code 204 only works with a `response_size` of 0 in the http server, hence this behavior. 
@kelson42 For this bug, I think a response code of 404 is more apt and will fix this issue.

**Comment by maneeshpm** [comment]
> 10.2.5 204 No Content
> 
> The server has fulfilled the request but does not need to return an entity-body, and might want to return updated metainformation. The response MAY include new or updated metainformation in the form of entity-headers, which if present SHOULD be associated with the requested variant.
> 
> If the client is a user agent, it SHOULD NOT change its document view from that which caused the request to be sent. This response is primarily intended to allow input for actions to take place without causing a change to the user agent's active document view, although any new or updated metainformation SHOULD be applied to the document currently in the user agent's active view.
> 
> The 204 response MUST NOT include a message-body, and thus is always terminated by the first empty line after the header fields.

What we see is not actually a bug, but an expected behavior of response code 204. I think in our case, a response code 200 with an appropriate message (or an empty json list in case of REST) is better. Sites like Wikipedia follow the same behavior.

**Comment by kelson42** [comment]
@maneeshpm You might be right, seems the bug has been introduce by attempting to implement https://github.com/kiwix/kiwix-lib/issues/393. Not clear to me if we can at the same time achieve to keep the solution for #393 and fix this ticket as well.

**Comment by maneeshpm** [comment]
In my opinion, we must get rid of 204 since it is enforced by the server and it is not its expected behavior. If necessary, we can give some other status code that isn't already being used and is not specified. Then we can add a unit test to signify the updated behavior.

**Comment by kelson42** [comment]
@maneeshpm Make sense, les wait feedback of @mgautierfr on this.

**Comment by maneeshpm** [comment]
@mgautierfr Do you think we should go back to returning a 200 status code and let the client handle it based on the response we return?

**Comment by kelson42** [comment]
@mgautierfr ?

**Comment by mgautierfr** [comment]
Yes, we should go back to 200. As the spec says, 204 is just "ok". But we want to display a empty page.
