### ISSUE TITLE
Buggy test zim examples.zim should be replaced

### ISSUE THREAD

**Issue by maneeshpm** [kiwix/kiwix-lib#467]
Refer openzim/libzim#521
A test zim file [examples.zim](https://github.com/kiwix/kiwix-lib/blob/baed447dd38a29342a3f509151d6d274774e0a32/test/data/example.zim) is incorrectly written and should be replaced to avoid any future confusion.

**Comment by kelson42** [comment]
@veloman-yunkan I think you had generated that file. If this bug was on purpose, please let us know.

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan I think you had generated that file. If this bug was on purpose, please let us know.

I have nothing to do with example.zim.

```
$ git log test/data/example.zim
commit 0630298fb9d8b63b88fc7043e53041c2ced5d529
Author: luddens <pierre.luddens@epitech.eu>
Date:   Mon Apr 20 18:04:42 2020 +0200

    Manager::addBookFromPathAndGetId unit test
```

**Comment by kelson42** [comment]
@veloman-yunkan OK, sorry about that. My misunderstanding.

**Comment by maneeshpm** [comment]
This issue should be resolved only after openzim/libzim#522 is merged so that we can generate a zim file with proper indexing of HTML content.

**Comment by kelson42** [comment]
@maneeshpm Do you still plan to upload a new version of the ZIM file?

**Comment by maneeshpm** [comment]
@kelson42 Thanks for the reminder :+1:. I have opened a PR.
