### ISSUE TITLE
<link type="root" ...> must be injected even if the taskbar is disabled

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#473]
`<link type="root" href="{{root}}">` is placed in head_part.html which is rendered only if `m_withTaskbar` is true,
it should be moved to `index.html`.

**Comment by veloman-yunkan** [comment]
No, it shouldn't be moved to `index.html`. That template is used for rendering only the homepage of the library.

**Comment by MananJethwani** [comment]
then @veloman-yunkan what do you propose?.....should I make a new HTML file which should always be added while creating response?

**Comment by veloman-yunkan** [comment]
@MananJethwani What other options can you think of?

**Comment by MananJethwani** [comment]
Instead of making a separate html page just for a link I can try embedding it directly through c++

**Comment by veloman-yunkan** [comment]
So if we go with a new HTML template, I think that we will name it something like `head_common.html`, and it makes sense to rename `head_part.html` to `head_taskbar.html`. `<link type="root" href="{{root}}">` will move from the latter to the former. While `head_common.html` is going to consist of that single line we can just insert that line directly. Introducing `head_common.html` now will lower the barrier for adding more stuff to it, including in the cases when that could be avoided. So let's postpone the creation of `head_common.html` (only mentioning that possibility in a code comment) but still rename `head_part.html` to `head_taskbar.html`.
