### ISSUE TITLE
abnormal behaviour of links

### ISSUE THREAD

**Issue by MananJethwani** [kiwix/kiwix-lib#477]
while trying to solve openzim/mwoffliner#904 while writing a relative path from an article named `/dev/zero` to `/dev` the href was supposed to be `..` but using it the site moves from `/dev/zero` to `/` that's 2 level up. here is some proof -> 

![Screenshot from 2021-03-25 01-32-59](https://user-images.githubusercontent.com/50267986/112528476-32324e80-8dca-11eb-92d2-336479406503.png)
![Screenshot from 2021-03-25 01-32-48](https://user-images.githubusercontent.com/50267986/112528514-3eb6a700-8dca-11eb-88ca-0314a9a15eb0.png)
also attached is the zip file containing the zim file I was testing ->
[wiktionary_en_mwo-test-10_2021-03.zip](https://github.com/kiwix/kiwix-lib/files/6207227/wiktionary_en_mwo-test-10_2021-03.zip)

**Comment by kelson42** [comment]
@MananJethwani It does not seem to be the right ZIM file.
