### ISSUE TITLE
Remove redirect to article in search

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-lib#481]
Following #464, we now have the redirect code in search request (https://github.com/kiwix/kiwix-lib/blob/master/src/server/internalServer.cpp#L500-L522) which somehow become useless.

It may broke a API (if someone use the search api with the article title to directly go to the article (in case of bookmark)), but I think this is something we can accept.

**Comment by kelson42** [comment]
@MananJethwani Maybe you can tackle this one as this is the follower of your PR

**Comment by MananJethwani** [comment]
@kelson42 sure will start working on this.
P.S. - sorry for the late reply
