### ISSUE TITLE
Unable to build kiwix-lib on Debian (packaging)

### ISSUE THREAD

**Issue by copyninja** [kiwix/kiwix-lib#49]
Hi,

I'm trying to build Debian package for kiwix-lib and have added `libzim-dev` `libpugixml-dev` and all other dependencies. But meson fails to find `libzim`

```
mkdir build && meson . build
WARNING: You are using 'ANSI_X3.4-1968' which is not a a Unicode-compatible locale.
WARNING: You might see errors if you use UTF-8 strings as filenames, as strings, or as file contents.
WARNING: Please switch to a UTF-8 locale for your platform.
The Meson build system
Version: 0.40.0
Source dir: /build/kiwix-lib-0.1
Build dir: /build/kiwix-lib-0.1/build
Build type: native build
Project name: kiwixlib
Native cpp compiler: c++ (gcc 6.3.0)
Build machine cpu family: x86
Build machine cpu: i686
Dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (0.29)
Native dependency icu-i18n found: YES 57.1

Meson encountered an error in file meson.build, line 10, column 0:
Native dependency 'libzim' not found
```
If I comment ouf dependency(libzim) line in `meson.build` it then fails to find pugixml.  More closer look on meson's build log indicates that its trying to find libzim using pkg-config but libzim package does not ship pkg-config file, same with pugixml. Which means probably it needs custom meson snippets to detect these library similar to ctpp2 snippet in current meson.build file.

Can you please help us to get it built properly?.

**Comment by kelson42** [comment]
@mgautierfr Can you please @copyninja a hint (or a fix)?

**Comment by mgautierfr** [comment]
The libzim packaged in debian is too old. It uses a version without pkg-config file.

For pugixml it is globaly the same problem but a bit more complex :
- The documented way to use pugixml is to include the pugixml files directly in the user code build system. 
- Before kiwix-lib (in kiwix) we where building a lib by directly calling `gcc` and then link to that lib.
- When I move kiwix-lib code into a separated project and use kiwix-build, I replace the direct `gcc` calls to a meson file (who generate a pkg-config file) and use it in kiwix-build.
- However, it seems that there is also a CMake to build pugixml (and pkg-config file if the right option is given) provided with pugixml.
- But It seems debian package use a custom Makefile (https://anonscm.debian.org/cgit/collab-maint/pugixml.git/tree/Makefileore) to compile pugixml. And this Makefile do not generate pkg-config file.

So there are several things to do here :
- On our side : Use the CMake file provided by pugixml  to compile it and stop using a custom meson file.
- On debian side : Package the last version of libzim and compile pugixml package using the provided CMake file.

**Comment by mgautierfr** [comment]
Well, it seem that the Makefile used by debian IS the makefile provided by pugixml.
But, pugixml packaged by debian is `1.7`. The last release `1.8` (November 2016) add the new CMake with the pkg-config file.
So debian should package the last version of pugixml and use the CMake build system.

**Comment by copyninja** [comment]
I'm the package maintainer for both zimlib and pugixml. Yes I can package latest pugixml which I did not do because of the freeze. But for zimlib I see the latest released version is 1.4 as seen [here](http://www.openzim.org/wiki/Releases) and it is packaged already in Debian. Did the upstream forget to release new changes of zimlib?.

**Comment by mgautierfr** [comment]
Oh. You're totally right, the zimlib 1.4 doesn't have the pkg-config support (neither in Makefile or in the through the new meson build system)

We definitly should make a new release of libzim. (But I would like to investigate on https://github.com/kiwix/kiwix-tools/issues/25 first)

While we are here, we changed the libzim repository location. It is now on github (https://github.com/openzim/libzim). The repository contains only the source of libzim and not all the openzim sources (with zimwriterfs) as before.
We also change the name from `zimlib` to `libzim`. As we are the only one user of libzim I know about, I think it will not be a problem but I may have wrong. Please let me know.

**Comment by copyninja** [comment]
OK noted the changed location for libzim. Changing name should not matter because library was named as libzim0 in Debian (and later changed libzim0v5 for gcc-5 transition but should be reverted to its original name).  Also `apt-cache rdepends` does not show any other package depending on this package. So yes it should be safe for the rename. 

So till the libzim new version is released I will hold the packaging work and mean time I will update pugixml to latest release.

**Comment by kelson42** [comment]
@copyninja Thank you for updating pugixml Debian package. I just have made this operation manually and it worked pretty well with pugixml 1.8. You just need to call cmake with the right option:
`cmake -DBUILD_PKGCONFIG=ON`

**Comment by kelson42** [comment]
@copyninja What is the status of that bug?

**Comment by legoktm** [comment]
I updated the status on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=856552#15 - the packaging is mostly done, but blocked on upgrading libzim in Debian to 2.0.0.

**Comment by kelson42** [comment]
@legoktm @copyninja  That is really good news. Unfortunately, I have kind of problem to identify what is the blocking issue with libzim packaging (and there is something we should/could do upstream to find it).

**Comment by legoktm** [comment]
libkiwix is currently waiting for review in the Debian NEW queue - https://ftp-master.debian.org/new/libkiwix_0.2.0-1.html

**Comment by kelson42** [comment]
I think I can close that ticket as the ticket problem has been resolved.

**Comment by samkellerhals** [comment]
Can confirm that on latest Raspbian stretch v.9.9 pugixml is not found during meson build process.

Compiling latest version of pugixml and using `-DBUILD_PKGCONFIG=1` and `DBUILD_SHARED_LIBS=1` options during `cmake` build fixes this.
