### ISSUE TITLE
Don't save the .meta4 file in the download directory

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#501]
It should stay "invisible" for the user and therefore stored in the profile directory.

@Popolechien reported that it is saved in the same directory like the ZIM file.

**Comment by mgautierfr** [comment]
We could use `--follow-metalink=mem` (https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-follow-metalink) to tell aria to not save the meta4 file.

**Comment by kelson42** [comment]
Sounds to be a top solution.

**Comment by kelson42** [comment]
I will try this.
