### ISSUE TITLE
Unable to build using meson due to pugixml dependency

### ISSUE THREAD

**Issue by legoktm** [kiwix/kiwix-lib#6]
I'm pretty new to meson, so I'm not sure if I'm doing something totally wrong...but I can't get this to build with meson. Here's what I did:

```
# apt install build-essential liblzma-dev libicu-dev libpugixml-dev
# Install libzim with https://gerrit.wikimedia.org/r/#/c/329759/ so pkg-config knows about it
# Edit meson.build to use "libzim" instead of "zimlib" (will submit a PR momentarily)
# mkdir build
# meson . build
The Meson build system
Version: 0.37.1
Source dir: /home/km/projects/kiwix-lib
Build dir: /home/km/projects/kiwix-lib/build
Build type: native build
Project name: kiwixlib
Native cpp compiler: c++ (gcc 6.2.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (0.29)
Native dependency icu-i18n found: YES 57.1
Native dependency libzim found: YES 1.4

Meson encountered an error in file meson.build, line 10, column 0:
Native dependency 'pugixml' not found
```
pugixml is definitely installed, and I know that meson uses pkg-config to find dependencies, so I filed https://github.com/zeux/pugixml/issues/128, but in the meantime, how do I build this?

**Comment by legoktm** [comment]
OK, it turns out that the Debian version of libpugixml is a bit old, and doesn't provide a pkg-config file. I built the library manually (using -DBUILD_PKGCONFIG=1) and made it further before running into:
```
...
[19/19] Linking target src/libkiwix.so
FAILED: src/libkiwix.so 
c++    -o src/libkiwix.so 'src/kiwix@sha/static_kiwixlib-resources.cpp.o' 'src/kiwix@sha/library.cpp.o' 'src/kiwix@sha/manager.cpp.o' 'src/kiwix@sha/reader.cpp.o' 'src/kiwix@sha/searcher.cpp.o' 'src/kiwix@sha/indexer.cpp.o' 'src/kiwix@sha/common_base64.cpp.o' 'src/kiwix@sha/common_pathTools.cpp.o' 'src/kiwix@sha/common_regexTools.cpp.o' 'src/kiwix@sha/common_stringTools.cpp.o' 'src/kiwix@sha/common_networkTools.cpp.o' 'src/kiwix@sha/common_otherTools.cpp.o' 'src/kiwix@sha/ctpp2_CTPP2VMStringLoader.cpp.o' 'src/kiwix@sha/xapian_htmlparse.cc.o' 'src/kiwix@sha/xapian_myhtmlparse.cc.o' 'src/kiwix@sha/xapianIndexer.cpp.o' 'src/kiwix@sha/xapianSearcher.cpp.o' '-Wl,--no-undefined' '-Wl,--as-needed' '-shared' '-fPIC' '-Wl,-soname,libkiwix.so' '-pthread' '-licui18n' '-licuuc' '-licudata' '-L/usr/local/lib' '-lzim' '-lctpp2' '-lxapian' '-L/usr/local/lib/pugixml-1.8' '-lpugixml' '-Wl,-rpath,/home/km/projects/kiwix-lib/build/src' 
/usr/bin/ld: /usr/local/lib/pugixml-1.8/libpugixml.a(pugixml.cpp.o): relocation R_X86_64_PC32 against symbol `_ZnwmPv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
```
Will investigate that later.

Leaving this open since we should document that most people will need a custom build of pugixml to build this.

**Comment by zeux** [comment]
@legoktm This is probably because you should build & install with -DBUILD_PKGCONFIG=1 -DBUILD_SHARED_LIBS=1. The linking is failing because pugixml is built as a static library but unfortunately to link with a static library you have to know in advance whether you're linking it into an executable or not (or to be more precise, into positionally-dependent executable or not), and the defaults in CMakeLists.txt don't match this use. I believe the binary that comes with Debian package is built as shared by default.

**Comment by legoktm** [comment]
@zeux thanks! With both of those options set, I was able to fully build this :) I've documented the required settings in #8.

**Comment by mgautierfr** [comment]
From the documentation : «The easiest way to build pugixml is to compile the source file, pugixml.cpp, along with the existing library/executable.» and previous makefile scripts compile itself pugixml.cpp without using any build script provided by pugixml. So I stop there :)

As I didn't want to compile myself pugixml (launch gcc with right arguments) I've created a Meson script for this (https://github.com/kiwix/kiwix-tools/blob/master/scripts/kiwix-builder/patches/pugixml_meson.patch). The kiwix-builder handle all this automatically.

**Comment by kelson42** [comment]
@legoktm Thank you for opening a ticket on Debian side, it's important that thing compile smoothly https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849810
