### ISSUE TITLE
Licensing kiwix-lib so it can be used by kiwix-apache

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-lib#60]
Kiwix-apache uses the Apache 2.0 license as it's primary audience is for users and contributors to the Apache Web Server project. It currently uses kiwix-lib. Collectively we would like to make sure that we've got compatible licenses for kiwix-lib, and if necessary it's dependencies so that both the Apache community and GPL communities accept that the licenses are compatible and acceptable to the various contributors of the respective projects.

Note: There are 15 contributors to kiwix-lib according to https://github.com/kiwix/kiwix-lib/graphs/contributors currently.

**Comment by kelson42** [comment]
What are the options we have? So far I can wee, this library should probably be GPLv2+ or GPLv3!? Do we have a concrete problem with one of them? Apache modules are load dynamically so it should not be theoritically a problem to use the GPL.

**Comment by julianharty** [comment]
I don't know enough on the licensing compatibilities to provide a definitive answer on which license to use for kiwix-lib, sorry. For now, how about we aim to use GPLv3+ for kiwix-lib and make sure that we compile and link kiwix-apache uses kiwix-lib dynamically. We may learn more about what license is necessary as this project matures.

**Comment by kelson42** [comment]
AFAIK, the current licensing is "clean" and is GPLv3+. This choice is not random and I suspect that many core developers of the kiwix-lib want to stick to a GPL license (if not the GPLv3 specifically).

That makes having kiwix-apache illegal to be distributed with a kiwix-apache license AFAIK (and with the GPLv2+ the problem would be the same).

So, as changing the license of the kiwix-lib might be really difficult, to me the question behind this ticket is more: what kind of problem do we have if kiwix-apache does not use an Apache license (a GPL for example)? See https://github.com/kiwix/kiwix-apache/issues/15

@mgautierfr @julianharty @cscott Any thoughts about that?

**Comment by orblivion** [comment]
In case this helps:

* https://www.apache.org/licenses/GPL-compatibility.html
* https://www.gnu.org/licenses/license-list.en.html#apache2

Apache 2.0 is compatible with GPL3. Apache 2.0 is _not_ compatible with GPL2.

**Comment by julianharty** [comment]
@orblivion sadly not in the way we want to combine things. "Apache 2 software can therefore be included in GPLv3 projects, because the GPLv3 license accepts our software into GPLv3 works. **However, GPLv3 software cannot be included in Apache projects.** " I'm trying to incorporate kiwix-lib (GPL v3.0) into kiwix-apache (Apache 2.0) https://github.com/kiwix/kiwix-lib/blob/master/COPYING

**Comment by legoktm** [comment]
Maybe I'm missing something, but why does kiwix-apache need to be Apache 2.0 licensed? According to <https://en.wikipedia.org/wiki/List_of_Apache_modules> there are GPL licensed modules.

**Comment by kelson42** [comment]
@legoktm kiwix-apache does not have to be Apache 2.0 licensed. But if not (so GPL) then this only translate a bit the problem. Because, AFAIK the problem is that it is not allowed to distribute Apache 2.0 licensed software linking (dynamically) against GPL library. So:
* If kiwix-apache is GPL, then kiwix-apache might be distributed properly, but any solution providing both bundled (kiwix-apache & kiwix) would be forbidden
* If kiwix-apache is Apache 2.0 then this is the module itself which will be forbidden to distribute as it links again libkiwix.

This is the theory we try to confirm currently.

**Comment by kelson42** [comment]
I close the ticket as everything seems to be OK here. Lets focus now on the kiwix-apache repo. license.
