### ISSUE TITLE
Update JNI API with multizim/byterange support

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-lib#67]
For multizim search, we need to update the JNI API.
However, if we update it right now, the kiwix-android project will break.

To discuss with kiwix-android team.

**Comment by kelson42** [comment]
@mgautierfr @mhutti1 Libkiwix 1.0.0 will be released ASAP and then the multizim/byterange will be introduced in the JNI. @mhutti1 You could then be able to deal with it. Hope that works for everyone.

**Comment by kelson42** [comment]
More urgent than ever as we really need to have the video play/code range access working on Android in the next weeks :(

**Comment by mhutti1** [comment]
@kelson42 is the jni side done?

**Comment by kelson42** [comment]
@mhutti1 No, not that I know, but this is definitly now the TOP prio for @mgautierfr. Should be done next week hopefully. Sorry for the big dealy on this... it unfortunately went a bit out of radar these last 3-4 weeks.

**Comment by kelson42** [comment]
@mhutti1 AFAIK this is now done.
@mgautierfr I close the ticket, please reopen if I'm wrong.

**Comment by mhutti1** [comment]
I have made some changes and a fix to the JNI to get this working. I will make a pull request once I have a demo of this.
