### ISSUE TITLE
src/android/kiwix.cpp is missing GPL file header

### ISSUE THREAD

**Issue by legoktm** [kiwix/kiwix-lib#71]
The history is a little hard to track, but I think it originated in https://github.com/kiwix/kiwix-android/commit/239daec094ba809688af5c6ea850607b0034d17c

**Comment by legoktm** [comment]
Also the java files under src/android just say `Copyright 2013`, but not who owns the copyright...?

**Comment by kelson42** [comment]
Most of the missing part of the history is here https://github.com/kiwix/kiwix-xulrunner/commits/master/android/kiwix.c. I have created this file in first Kiwix for Android hackathon, back in 2013. Then they have been modified by a few of our developers.

**Comment by kelson42** [comment]
@legoktm I think I have fixed the problem, please let me know if the PR is OK for you https://github.com/kiwix/kiwix-lib/pull/72
