### ISSUE TITLE
Reader constructor crash when opening a non-zim file

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-lib#85]
### Issue
If passing a path to a non-zim file, e.g., a zip file to constructor of `kiwix::Reader`, the library will abort. [Line that aborted](https://github.com/openzim/libzim/blob/master/src/file_reader.cpp#L104)
### Desired Behavior
throw an exception instead of abort

**Comment by kelson42** [comment]
@automactic Could you please upload an example here of such a file?

**Comment by automactic** [comment]
You could reproduce this problem using any non-zim file. So far I have been able to reproduce it with a zip, a mp4, a pdf and a jpg. 

BTW, you could see the call stack by using [kiwix for macOS](https://www.dropbox.com/sh/4ylznhluftxqags/AADTpyYXO7-c_Bfio55j2mMGa?dl=0) app, open a non-zim file, after app crash, click on report

**Comment by mgautierfr** [comment]
Yes, I add those assert with the last rewrite of the libzim.
It's something that should be fixed.

It's a `libzim` bug, so I'm closing this issue here.
