### ISSUE TITLE
Search title has html tags

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-lib#87]
Calling `kiwix::Result::get_title` sometimes results in a string with html tags. 

For example, in `wikipedia_en_medicine_novid_2017-08.zim`, if search 't', you can get results with title like `<I>Thermococcus</i>`

**Comment by kelson42** [comment]
@automactic I'm quite sure this is a bug in mwoffliner.

**Comment by kelson42** [comment]
This issue was moved to openzim/mwoffliner#159
